name: Fetch Dependabot Metadata

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  extract-metadata:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Fetch Dependabot Metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1

      - name: Add Labels Based on Metadata
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GH_PAT }}
          labels: |
            package:${{ steps.metadata.outputs.package }}
            from:${{ steps.metadata.outputs.previous-version }}
            to:${{ steps.metadata.outputs.new-version }}
            update-type:${{ steps.metadata.outputs.update-type }}
